//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfUPractika.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int ID { get; set; }
        public int OfferId { get; set; }
        public int NeedId { get; set; }
    
        public virtual Need Need { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
