//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfUPractika.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Need
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Need()
        {
            this.Deal = new HashSet<Deal>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> RealtorId { get; set; }
        public Nullable<int> TypePropertyId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deal { get; set; }
        public virtual Realtor Realtor { get; set; }
        public virtual TypeProperty TypeProperty { get; set; }
    }
}
