//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfUPractika.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Login { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> RealtorId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Realtor Realtor { get; set; }
        public virtual Role Role { get; set; }
    }
}
